### ISSUE TITLE
Plexamp support

### ISSUE THREAD

**Issue by acidkill** [ItsRiprod/DeskThing#17]
Add support for controlling music playback from Plexamp: https://www.plex.tv/plexamp/

**Comment by ItsRiprod** [comment]
Great idea! I meant to reply to this sooner

I just added it to the trello https://trello.com/b/6v0paxqV/deskthing

If you want to be able to vote for upcoming apps, I highly recommend joining the discord and going to [this thread](https://canary.discord.com/channels/1042954149786046604/1257429709764169818) where I post a poll (roughly) every release for the next set of features

There's been a couple people on the server who have also suggested plexamp controls, so I could see it gaining some traction.
