### ISSUE TITLE
[Request] Raspberry Pi

### ISSUE THREAD

**Issue by ultimateshadsform** [ItsRiprod/DeskThing#66]
Raspberry pi compatible?

Hi just wondering. I already have a raspberry pi with a touch screen.

Could this project just be ran in kiosk mode to have it as a media player without having an actual Car Thing?

Would be a nice addition.

**Comment by ItsRiprod** [comment]
Yes! It would

You can go to the Clients tab and there's a QR code button that will have the URL you can go to from any device on your network (phone, tablet, fridge, etc) 

Basically anything with a browser should work

**Comment by ultimateshadsform** [comment]
Oh neat!!!! Thanks!!
