### ISSUE TITLE
Intempestive deconnection

### ISSUE THREAD

**Issue by Alfly-Alyx** [ItsRiprod/DeskThing#77]
The Carthing is deconnected after an hour about and deskthing cannot find it unless I unplug and replug the Carthing.

**Comment by dylanface** [comment]
Intempestive deconnection = deskthing disconnects and will not reconnect if the power state changes on the host computer

**Comment by ItsRiprod** [comment]
There is a guide for fixing this on the discord until I can make it part of the default image! I just finished it under the Resources channel

I know it's not the best fix - but it'll be the fix used until we can use a different image - will update once a better solution is found (if i remember)

**Comment by Alfly-Alyx** [comment]
> Intempestive deconnection = deskthing disconnects and will not reconnect if the power state changes on the host computer

Not if the power state changes. It disconnects a few times (about 30mins) after to be plugged.
But I changed the USB selective power off setting, I switch off the parameter.

**Comment by NotNite** [comment]
> There is a guide for fixing this on the discord until I can make it part of the default image! I just finished it under the Resources channel

For the record, it's a zip file that uploads some files via adb: <https://cdn.discordapp.com/attachments/1304902607248166934/1305017084840771647/restart_adb.zip>. You can paste this URL into a Discord channel in order for it to generate the proper query parameters to access it.

I don't appreciate having to join a server to fix a pretty crucial bug with this software - please put this somewhere that is public on the Internet.

**Comment by ItsRiprod** [comment]
Understood! It's not ideal 
>>> but it'll be the fix used until we can use a different image

I definitely don't plan on leaving it there. The discord has several guides on it as a temporary hotfix until i can make a formally documented fix.
