### ISSUE TITLE
App requests persist even after app has been purged

### ISSUE THREAD

**Issue by petitchou** [ItsRiprod/DeskThing#78]
If you install an app, run it without answering its request, and then purge it, the request persists and waits to be answered.

I noticed this today with the Discord app. 

I have not attempted to duplicate it. My Deskthing install appears to be a bit... touchy (which is not your fault!), or otherwise I'd try to test it elsewhere. But this should be simple to duplicate.

**Comment by ItsRiprod** [comment]
This is a known issue. If you notice the banner in the requests tab, they are being phased out and being replaced with a "Task" based system (like the demo you saw when setting up) which apps can add to better guide you in setting up the apps

Good catch though 
Also, the next update should bring a lot more stability improvements to the whole thing - so hopefully it'll be less touchy

**Comment by petitchou** [comment]
Okay! I saw the banner but I wasn't sure if it was something you'd want to fix before then or not, so I thought I'd go ahead and file a bug report anyhow - figured you'd rather know than not if you didn't already.

Looking forward to the new version. Thanks so much for your hard work - this is really incredible!
